// Code generated by vfsgen; DO NOT EDIT.

// +build !dev

package assets

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	pathpkg "path"
	"time"
)

// FileSystem contains project assets.
var FileSystem = func() http.FileSystem {
	fs := vfsgen۰FS{
		"/": &vfsgen۰DirInfo{
			name:    "/",
			modTime: time.Date(2018, 8, 9, 1, 35, 27, 185389234, time.UTC),
		},
		"/controls.js": &vfsgen۰CompressedFileInfo{
			name:             "controls.js",
			modTime:          time.Date(2018, 8, 9, 1, 51, 39, 819214310, time.UTC),
			uncompressedSize: 917,

			compressedContent: []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\x92\x51\x6b\xdb\x30\x14\x85\x9f\xed\x5f\x71\x07\x1d\xb6\x21\x28\xef\x0d\x1e\x84\xac\xd0\x41\x07\x63\xcd\xde\x2d\xe4\xe3\xda\x54\xb9\x72\xe5\xab\xd0\x11\xfc\xdf\x87\xe4\x2e\xa4\xd0\x8c\x3d\x4a\x5c\x9d\xf3\x9d\x73\x65\x1c\x4f\x42\x3d\x74\x0b\x3f\x51\x4d\xa7\x3c\xdb\x1a\x83\x51\x6e\xa9\x10\xbc\xca\x7a\xb4\x7a\xe0\x62\x95\xcf\x9b\x3c\x5f\x86\xe1\xbd\xf3\x77\x16\x07\xaa\xa9\x75\x26\x1c\xc0\xa2\x5e\x02\xfc\xef\x47\x58\x18\x71\xbe\x2c\x54\x1a\x2a\xaa\xf3\xa3\x0e\x62\xfa\x7d\x0f\xa6\x9a\x3c\xa6\x91\xea\x2f\xd1\x6b\xe8\xa8\x8c\x47\xe5\x9e\xab\x78\xce\xce\xe2\x2a\xba\xef\x1c\x0b\x58\xa8\xa6\xa2\xd8\xe4\xd9\x4c\xb0\x13\xd2\x5c\x54\x75\x16\x8b\x4f\x59\x24\x79\xf2\x78\x09\x88\x66\x7a\xb0\x68\x6f\xa9\x58\x25\xaf\x48\x71\x5d\xb9\xd9\xd2\xfd\x7e\xff\x63\x89\x45\xce\x98\xe0\x7d\x7c\x7c\x73\x4a\x60\x93\x68\x09\xd3\xfc\xfe\xb8\xc7\xab\xcc\xaa\x89\x48\x17\xc5\x24\x88\x9d\x8e\x24\x35\xe1\x2d\xe1\x3f\x41\xd3\x65\xe2\x44\x82\xbc\xce\xc8\x1f\xf0\x41\x89\x7b\x14\x3f\xf0\x53\x59\xcd\xcd\x26\x91\x5c\x5d\x88\x71\x2c\xde\xd9\xa9\xa8\x94\x6e\xdb\xbb\x23\x58\x1e\x86\x49\xc0\xf0\x65\x61\xec\x60\x9e\x23\xc5\xc5\x5a\x3e\x95\x50\xa2\xfd\x13\x84\x06\x9e\x44\xb3\x81\xeb\xe8\x7e\xff\xfd\x61\xcb\xa6\x5f\x30\xc1\x52\x2d\x7b\xf3\x90\xe0\x39\x15\x92\x67\x50\xa3\x47\x74\xf8\x8a\x4e\x07\x2b\x65\xb5\xc9\xb3\x94\xfc\xac\xa9\x7a\x8f\x6e\x45\xa7\xb7\x9f\x37\x57\x4a\x7a\x70\x79\xfe\x26\xab\x8b\x36\xab\x4d\x3e\xaf\xa8\xd3\x76\x4a\x2d\x5d\x8d\x78\x74\x36\x1c\xf0\x61\xc0\x81\xc7\x20\x17\x01\xcf\x18\x32\x88\x45\x6c\x38\xd5\xb9\xdc\x1d\xb5\x0d\x98\x3f\x37\x71\x23\x0b\x75\xb3\xfe\x5b\xdf\x7a\x31\x59\xdf\x9c\xc0\xc6\xb5\xf8\xf5\xf3\xdb\xce\x1d\x46\xc7\x60\x29\xdf\x2b\x54\x73\x73\x19\x30\xcf\xb2\xff\xcd\xf8\x27\x00\x00\xff\xff\x71\x10\x3b\x21\x95\x03\x00\x00"),
		},
		"/style.css": &vfsgen۰CompressedFileInfo{
			name:             "style.css",
			modTime:          time.Date(2018, 8, 9, 1, 14, 31, 747522133, time.UTC),
			uncompressedSize: 446,

			compressedContent: []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x90\xc1\x6e\x02\x21\x10\x86\xcf\xf2\x14\x93\xf4\x2a\x1b\xd7\x6e\x4d\xc3\xa6\x4f\xd2\xf4\x80\x30\x65\x89\x38\x43\x70\xac\xbb\x36\xbe\x7b\xc3\x6a\x3d\x34\x8d\x37\xf8\xf3\x7d\xcc\xcf\x6c\xd9\x4f\xf0\xad\x16\x7b\x3b\xea\x53\xf4\x32\x18\xd8\xbc\xac\xf2\xd8\xab\x9a\x95\x10\xc9\x40\xb7\xca\x23\xd8\xa3\x70\xaf\x16\xd9\x7a\x1f\x29\x18\x58\x41\x7b\xc3\x3e\x99\x44\x1f\xe2\x19\x0d\xb4\xaf\x35\x5a\xa4\x48\xa8\x07\x8c\x61\x10\x03\x6d\xb3\xa9\x94\xe3\xc4\xc5\xc0\x53\xd7\x75\xbd\xba\x28\x35\xb4\x4b\x18\xd6\x4b\x18\x9e\xeb\xf8\x3f\xc6\x7a\x46\x9a\x6c\x03\xea\x9c\xec\x94\xe2\x41\xa0\xb1\x4e\xe2\x17\x56\x7c\x1e\x79\xba\xe1\x5b\x4e\xfe\x3f\x3e\x45\xb0\x4b\xb8\x86\x8e\x49\x0a\xa7\x03\x34\xf7\x93\xad\x0f\x5d\x5b\xdd\x4b\x3d\x86\x05\x47\xd1\x1e\x1d\x17\x2b\x91\xc9\x00\x31\xe1\x63\xef\xd7\xb2\x29\x06\x32\xe0\x90\x04\xcb\xac\x44\xca\x47\x79\x97\x29\xe3\x5b\xb1\x14\xf0\xc3\x18\xbd\xe7\xb3\x9e\x2f\x5a\x8a\x75\xbb\x6a\x6f\xad\xdb\x85\xc2\x47\xf2\xfa\xb6\xc1\x54\x7f\x1d\x0a\x4e\xbd\xba\xfc\x04\x00\x00\xff\xff\xe0\x1e\x73\x6d\xbe\x01\x00\x00"),
		},
	}
	fs["/"].(*vfsgen۰DirInfo).entries = []os.FileInfo{
		fs["/controls.js"].(os.FileInfo),
		fs["/style.css"].(os.FileInfo),
	}

	return fs
}()

type vfsgen۰FS map[string]interface{}

func (fs vfsgen۰FS) Open(path string) (http.File, error) {
	path = pathpkg.Clean("/" + path)
	f, ok := fs[path]
	if !ok {
		return nil, &os.PathError{Op: "open", Path: path, Err: os.ErrNotExist}
	}

	switch f := f.(type) {
	case *vfsgen۰CompressedFileInfo:
		gr, err := gzip.NewReader(bytes.NewReader(f.compressedContent))
		if err != nil {
			// This should never happen because we generate the gzip bytes such that they are always valid.
			panic("unexpected error reading own gzip compressed bytes: " + err.Error())
		}
		return &vfsgen۰CompressedFile{
			vfsgen۰CompressedFileInfo: f,
			gr: gr,
		}, nil
	case *vfsgen۰DirInfo:
		return &vfsgen۰Dir{
			vfsgen۰DirInfo: f,
		}, nil
	default:
		// This should never happen because we generate only the above types.
		panic(fmt.Sprintf("unexpected type %T", f))
	}
}

// vfsgen۰CompressedFileInfo is a static definition of a gzip compressed file.
type vfsgen۰CompressedFileInfo struct {
	name              string
	modTime           time.Time
	compressedContent []byte
	uncompressedSize  int64
}

func (f *vfsgen۰CompressedFileInfo) Readdir(count int) ([]os.FileInfo, error) {
	return nil, fmt.Errorf("cannot Readdir from file %s", f.name)
}
func (f *vfsgen۰CompressedFileInfo) Stat() (os.FileInfo, error) { return f, nil }

func (f *vfsgen۰CompressedFileInfo) GzipBytes() []byte {
	return f.compressedContent
}

func (f *vfsgen۰CompressedFileInfo) Name() string       { return f.name }
func (f *vfsgen۰CompressedFileInfo) Size() int64        { return f.uncompressedSize }
func (f *vfsgen۰CompressedFileInfo) Mode() os.FileMode  { return 0444 }
func (f *vfsgen۰CompressedFileInfo) ModTime() time.Time { return f.modTime }
func (f *vfsgen۰CompressedFileInfo) IsDir() bool        { return false }
func (f *vfsgen۰CompressedFileInfo) Sys() interface{}   { return nil }

// vfsgen۰CompressedFile is an opened compressedFile instance.
type vfsgen۰CompressedFile struct {
	*vfsgen۰CompressedFileInfo
	gr      *gzip.Reader
	grPos   int64 // Actual gr uncompressed position.
	seekPos int64 // Seek uncompressed position.
}

func (f *vfsgen۰CompressedFile) Read(p []byte) (n int, err error) {
	if f.grPos > f.seekPos {
		// Rewind to beginning.
		err = f.gr.Reset(bytes.NewReader(f.compressedContent))
		if err != nil {
			return 0, err
		}
		f.grPos = 0
	}
	if f.grPos < f.seekPos {
		// Fast-forward.
		_, err = io.CopyN(ioutil.Discard, f.gr, f.seekPos-f.grPos)
		if err != nil {
			return 0, err
		}
		f.grPos = f.seekPos
	}
	n, err = f.gr.Read(p)
	f.grPos += int64(n)
	f.seekPos = f.grPos
	return n, err
}
func (f *vfsgen۰CompressedFile) Seek(offset int64, whence int) (int64, error) {
	switch whence {
	case io.SeekStart:
		f.seekPos = 0 + offset
	case io.SeekCurrent:
		f.seekPos += offset
	case io.SeekEnd:
		f.seekPos = f.uncompressedSize + offset
	default:
		panic(fmt.Errorf("invalid whence value: %v", whence))
	}
	return f.seekPos, nil
}
func (f *vfsgen۰CompressedFile) Close() error {
	return f.gr.Close()
}

// vfsgen۰DirInfo is a static definition of a directory.
type vfsgen۰DirInfo struct {
	name    string
	modTime time.Time
	entries []os.FileInfo
}

func (d *vfsgen۰DirInfo) Read([]byte) (int, error) {
	return 0, fmt.Errorf("cannot Read from directory %s", d.name)
}
func (d *vfsgen۰DirInfo) Close() error               { return nil }
func (d *vfsgen۰DirInfo) Stat() (os.FileInfo, error) { return d, nil }

func (d *vfsgen۰DirInfo) Name() string       { return d.name }
func (d *vfsgen۰DirInfo) Size() int64        { return 0 }
func (d *vfsgen۰DirInfo) Mode() os.FileMode  { return 0755 | os.ModeDir }
func (d *vfsgen۰DirInfo) ModTime() time.Time { return d.modTime }
func (d *vfsgen۰DirInfo) IsDir() bool        { return true }
func (d *vfsgen۰DirInfo) Sys() interface{}   { return nil }

// vfsgen۰Dir is an opened dir instance.
type vfsgen۰Dir struct {
	*vfsgen۰DirInfo
	pos int // Position within entries for Seek and Readdir.
}

func (d *vfsgen۰Dir) Seek(offset int64, whence int) (int64, error) {
	if offset == 0 && whence == io.SeekStart {
		d.pos = 0
		return 0, nil
	}
	return 0, fmt.Errorf("unsupported Seek in directory %s", d.name)
}

func (d *vfsgen۰Dir) Readdir(count int) ([]os.FileInfo, error) {
	if d.pos >= len(d.entries) && count > 0 {
		return nil, io.EOF
	}
	if count <= 0 || count > len(d.entries)-d.pos {
		count = len(d.entries) - d.pos
	}
	e := d.entries[d.pos : d.pos+count]
	d.pos += count
	return e, nil
}
