// Code generated by vfsgen; DO NOT EDIT.

// +build !dev

package assets

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	pathpkg "path"
	"time"
)

// FileSystem contains project assets.
var FileSystem = func() http.FileSystem {
	fs := vfsgen۰FS{
		"/": &vfsgen۰DirInfo{
			name:    "/",
			modTime: time.Date(2018, 8, 8, 14, 30, 27, 805305174, time.UTC),
		},
		"/style.css": &vfsgen۰CompressedFileInfo{
			name:             "style.css",
			modTime:          time.Date(2018, 8, 8, 14, 36, 52, 806033984, time.UTC),
			uncompressedSize: 375,

			compressedContent: []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\xcf\x41\x6e\xeb\x20\x10\x06\xe0\x75\x38\xc5\x48\x6f\x1b\x22\x3b\xcf\x8d\x2a\xac\x9e\xa4\xea\x62\x0c\x14\x50\x08\x83\xf0\xb8\xb1\x53\xe5\xee\x15\x8e\xd5\x45\x95\x25\xbf\xbe\x61\xfe\x19\xc8\x2c\xf0\x2d\x76\x17\x9c\xe5\x35\x18\xf6\x0a\x4e\x2f\x4d\x9e\x7b\x51\xb3\xe2\x42\x52\xd0\x35\x79\x06\x9c\x98\x7a\xb1\xcb\x68\x4c\x48\x4e\x41\x03\xed\xc6\x3e\x29\xb1\x1c\xc3\xcd\x2a\x68\x5f\x6b\xb4\x8b\x21\x59\xe9\x6d\x70\x9e\x15\xb4\x87\x53\x55\x9a\x22\x15\x05\xff\xba\xae\xeb\xc5\x5d\x08\xdf\xee\xc1\x1f\xf7\xe0\xff\xd7\xf5\x7f\x26\x8e\x2b\x39\x64\x74\x56\xe6\x88\x4b\x0c\x23\xc3\x01\x35\x87\x2f\x5b\xf9\xba\xf2\xba\xf1\x81\xa2\x79\xe6\x63\x00\xdc\xc3\x23\xd4\x94\xb8\x50\x1c\x01\xeb\xf8\xa3\xcb\x6f\x95\x67\x84\xed\xcc\xd2\x58\x4d\x05\x39\x50\x52\x90\x28\xd9\x55\x87\x94\x27\x7e\xe7\x25\xdb\xb7\x82\xc9\xd9\x0f\xa5\xe4\x85\x6e\x72\x7d\x48\x2e\xa8\xcf\xf5\x83\x01\xf5\xd9\x15\x9a\x92\x91\xdb\xe9\xb1\xd6\x75\xc5\x2e\xbd\xb8\xff\x04\x00\x00\xff\xff\xa2\xda\x70\xdd\x77\x01\x00\x00"),
		},
		"/volume.js": &vfsgen۰CompressedFileInfo{
			name:             "volume.js",
			modTime:          time.Date(2018, 8, 8, 14, 30, 23, 683000000, time.UTC),
			uncompressedSize: 221,

			compressedContent: []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\xcc\xc1\x4a\x03\x31\x10\x06\xe0\x73\xf3\x14\x39\x08\x49\xa0\x4c\x1f\x60\xa9\x97\xe2\x41\xf0\xa4\x78\x6f\x48\xfe\xea\x42\x76\xa6\x4e\x26\x8b\x52\xf6\xdd\x45\x3c\x79\xf0\x01\xbe\xaf\x4a\x19\x0b\xd8\xe8\x63\x40\xbf\x5e\xd0\x50\x4c\x34\x06\xea\x6d\xae\xd0\x90\x28\xd7\xfa\xb0\x82\xed\x69\xee\x06\x86\xc6\x30\xf3\x75\x58\xd8\x7b\xf8\xe3\xbd\xbf\xb9\xdd\xbf\xc7\x2a\x6d\x2c\x08\x89\x0c\x9f\x76\x12\x36\xb0\xf9\xa3\x07\x59\xd6\x37\x18\xad\xb9\x0d\x4c\xce\xed\x2e\xb0\xf2\x1e\xcf\x87\x5f\x70\xb8\xbb\x81\x8b\x54\xbc\x3e\x3f\x9e\x64\xb9\x0a\x83\x2d\xfe\x55\x69\x3b\x27\x2a\xf9\x87\x15\xe1\x2e\x0d\x04\x55\xd1\x34\xb9\x6d\xef\x2f\xb9\x75\xa4\xe9\x3b\x00\x00\xff\xff\x6a\xc9\xc0\x4c\xdd\x00\x00\x00"),
		},
	}
	fs["/"].(*vfsgen۰DirInfo).entries = []os.FileInfo{
		fs["/style.css"].(os.FileInfo),
		fs["/volume.js"].(os.FileInfo),
	}

	return fs
}()

type vfsgen۰FS map[string]interface{}

func (fs vfsgen۰FS) Open(path string) (http.File, error) {
	path = pathpkg.Clean("/" + path)
	f, ok := fs[path]
	if !ok {
		return nil, &os.PathError{Op: "open", Path: path, Err: os.ErrNotExist}
	}

	switch f := f.(type) {
	case *vfsgen۰CompressedFileInfo:
		gr, err := gzip.NewReader(bytes.NewReader(f.compressedContent))
		if err != nil {
			// This should never happen because we generate the gzip bytes such that they are always valid.
			panic("unexpected error reading own gzip compressed bytes: " + err.Error())
		}
		return &vfsgen۰CompressedFile{
			vfsgen۰CompressedFileInfo: f,
			gr: gr,
		}, nil
	case *vfsgen۰DirInfo:
		return &vfsgen۰Dir{
			vfsgen۰DirInfo: f,
		}, nil
	default:
		// This should never happen because we generate only the above types.
		panic(fmt.Sprintf("unexpected type %T", f))
	}
}

// vfsgen۰CompressedFileInfo is a static definition of a gzip compressed file.
type vfsgen۰CompressedFileInfo struct {
	name              string
	modTime           time.Time
	compressedContent []byte
	uncompressedSize  int64
}

func (f *vfsgen۰CompressedFileInfo) Readdir(count int) ([]os.FileInfo, error) {
	return nil, fmt.Errorf("cannot Readdir from file %s", f.name)
}
func (f *vfsgen۰CompressedFileInfo) Stat() (os.FileInfo, error) { return f, nil }

func (f *vfsgen۰CompressedFileInfo) GzipBytes() []byte {
	return f.compressedContent
}

func (f *vfsgen۰CompressedFileInfo) Name() string       { return f.name }
func (f *vfsgen۰CompressedFileInfo) Size() int64        { return f.uncompressedSize }
func (f *vfsgen۰CompressedFileInfo) Mode() os.FileMode  { return 0444 }
func (f *vfsgen۰CompressedFileInfo) ModTime() time.Time { return f.modTime }
func (f *vfsgen۰CompressedFileInfo) IsDir() bool        { return false }
func (f *vfsgen۰CompressedFileInfo) Sys() interface{}   { return nil }

// vfsgen۰CompressedFile is an opened compressedFile instance.
type vfsgen۰CompressedFile struct {
	*vfsgen۰CompressedFileInfo
	gr      *gzip.Reader
	grPos   int64 // Actual gr uncompressed position.
	seekPos int64 // Seek uncompressed position.
}

func (f *vfsgen۰CompressedFile) Read(p []byte) (n int, err error) {
	if f.grPos > f.seekPos {
		// Rewind to beginning.
		err = f.gr.Reset(bytes.NewReader(f.compressedContent))
		if err != nil {
			return 0, err
		}
		f.grPos = 0
	}
	if f.grPos < f.seekPos {
		// Fast-forward.
		_, err = io.CopyN(ioutil.Discard, f.gr, f.seekPos-f.grPos)
		if err != nil {
			return 0, err
		}
		f.grPos = f.seekPos
	}
	n, err = f.gr.Read(p)
	f.grPos += int64(n)
	f.seekPos = f.grPos
	return n, err
}
func (f *vfsgen۰CompressedFile) Seek(offset int64, whence int) (int64, error) {
	switch whence {
	case io.SeekStart:
		f.seekPos = 0 + offset
	case io.SeekCurrent:
		f.seekPos += offset
	case io.SeekEnd:
		f.seekPos = f.uncompressedSize + offset
	default:
		panic(fmt.Errorf("invalid whence value: %v", whence))
	}
	return f.seekPos, nil
}
func (f *vfsgen۰CompressedFile) Close() error {
	return f.gr.Close()
}

// vfsgen۰DirInfo is a static definition of a directory.
type vfsgen۰DirInfo struct {
	name    string
	modTime time.Time
	entries []os.FileInfo
}

func (d *vfsgen۰DirInfo) Read([]byte) (int, error) {
	return 0, fmt.Errorf("cannot Read from directory %s", d.name)
}
func (d *vfsgen۰DirInfo) Close() error               { return nil }
func (d *vfsgen۰DirInfo) Stat() (os.FileInfo, error) { return d, nil }

func (d *vfsgen۰DirInfo) Name() string       { return d.name }
func (d *vfsgen۰DirInfo) Size() int64        { return 0 }
func (d *vfsgen۰DirInfo) Mode() os.FileMode  { return 0755 | os.ModeDir }
func (d *vfsgen۰DirInfo) ModTime() time.Time { return d.modTime }
func (d *vfsgen۰DirInfo) IsDir() bool        { return true }
func (d *vfsgen۰DirInfo) Sys() interface{}   { return nil }

// vfsgen۰Dir is an opened dir instance.
type vfsgen۰Dir struct {
	*vfsgen۰DirInfo
	pos int // Position within entries for Seek and Readdir.
}

func (d *vfsgen۰Dir) Seek(offset int64, whence int) (int64, error) {
	if offset == 0 && whence == io.SeekStart {
		d.pos = 0
		return 0, nil
	}
	return 0, fmt.Errorf("unsupported Seek in directory %s", d.name)
}

func (d *vfsgen۰Dir) Readdir(count int) ([]os.FileInfo, error) {
	if d.pos >= len(d.entries) && count > 0 {
		return nil, io.EOF
	}
	if count <= 0 || count > len(d.entries)-d.pos {
		count = len(d.entries) - d.pos
	}
	e := d.entries[d.pos : d.pos+count]
	d.pos += count
	return e, nil
}
